version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  celo:
    restart: "unless-stopped"
    stop_grace_period: 5m
    image: us.gcr.io/celo-org/geth:${CELO_DOCKER_TAG}
    volumes:
      - celo-data:/var/lib/celo
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${P2P_PORT}:${P2P_PORT}/tcp
      - ${P2P_PORT}:${P2P_PORT}/udp
    <<: *logging
    entrypoint:
      - sh
      - /run_geth_in_docker.sh
      - --datadir
      - /var/lib/celo
      - --syncmode
      - ${SYNCMODE}
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.port
      - ${RPC_PORT}
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api
      - eth,net,web3
      - --ws
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${WS_PORT}
      - --ws.api
      - web3,eth,net
      - --ws.origins=*
      - --port
      - ${P2P_PORT}
      - --metrics
      - --metrics.expensive
      - --pprof
      - --pprof.addr
      - 0.0.0.0
      - --light.serve
      - "90"
      - --light.maxpeers
      - "1000"
      - --maxpeers
      - "1100"
      - --verbosity
      - ${VERBOSITY}
      - --etherbase
      - ${CELO_ACCOUNT}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${RPC_HOST:-celo}.service=${RPC_HOST:-celo}
      - traefik.http.routers.${RPC_HOST:-celo}.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-celo}.rule=Host(`${RPC_HOST:-celo}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-celo}.tls.certresolver=letsencrypt
      - traefik.http.routers.${RPC_HOST:-celo}lb.service=${RPC_HOST:-celo}
      - traefik.http.routers.${RPC_HOST:-celo}lb.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-celo}lb.rule=Host(`${RPC_LB:-celo-lb}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-celo}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${RPC_HOST:-celo}.loadbalancer.server.port=${RPC_PORT}
      - traefik.http.routers.${WS_HOST:-celows}.service=${WS_HOST:-celows}
      - traefik.http.routers.${WS_HOST:-celows}.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-celows}.rule=Host(`${WS_HOST:-celows}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-celows}.tls.certresolver=letsencrypt
      - traefik.http.routers.${WS_HOST:-celows}lb.service=${WS_HOST:-celows}
      - traefik.http.routers.${WS_HOST:-celows}lb.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-celows}lb.rule=Host(`${WS_LB:-celows-lb}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-celows}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${WS_HOST:-celows}.loadbalancer.server.port=${WS_PORT}
      - metrics.scrape=true
      - metrics.path=/debug/metrics/prometheus
      - metrics.port=6060
  set-prune-marker:
    profiles: ["tools"]
    image: alpine:3
    user: "10001:10001"
    restart: "no"
    volumes:
      - celo-data:/var/lib/celo
    entrypoint: ["/bin/sh","-c"]
    command: /bin/sh

volumes:
  celo-data:
